#ifndef ANALYSER_QUANTITY_GLOBAL_H
#define ANALYSER_QUANTITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANALYSER_QUANTITY_LIBRARY)
#  define ANALYSER_QUANTITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALYSER_QUANTITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANALYSER_QUANTITY_GLOBAL_H
