#ifndef ANALYSER_QUALITY_GLOBAL_H
#define ANALYSER_QUALITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANALYSER_QUALITY_LIBRARY)
#  define ANALYSER_QUALITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALYSER_QUALITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANALYSER_QUALITY_GLOBAL_H
