#ifndef REPORT_RELATIVE_GLOBAL_H
#define REPORT_RELATIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORT_RELATIVE_LIBRARY)
#  define REPORT_RELATIVESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPORT_RELATIVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORT_RELATIVE_GLOBAL_H
