#ifndef REPORT_CALIBRATION_GLOBAL_H
#define REPORT_CALIBRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORT_CALIBRATION_LIBRARY)
#  define REPORT_CALIBRATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPORT_CALIBRATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORT_CALIBRATION_GLOBAL_H
