#ifndef ANALYSER_CALIBRATION_GLOBAL_H
#define ANALYSER_CALIBRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANALYSER_CALIBRATION_LIBRARY)
#  define ANALYSER_CALIBRATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALYSER_CALIBRATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANALYSER_CALIBRATION_GLOBAL_H
