#ifndef ANALYSER_RELATIVE_GLOBAL_H
#define ANALYSER_RELATIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANALYSER_RELATIVE_LIBRARY)
#  define ANALYSER_RELATIVESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALYSER_RELATIVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANALYSER_RELATIVE_GLOBAL_H
