#ifndef VIDEO_ARCHIVE_GLOBAL_H
#define VIDEO_ARCHIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIDEO_ARCHIVE_LIBRARY)
#  define VIDEO_ARCHIVESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIDEO_ARCHIVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIDEO_ARCHIVE_GLOBAL_H
