#ifndef ANALYSER_PEAKSAREA_GLOBAL_H
#define ANALYSER_PEAKSAREA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ANALYSER_PEAKSAREA_LIBRARY)
#  define ANALYSER_PEAKSAREASHARED_EXPORT Q_DECL_EXPORT
#else
#  define ANALYSER_PEAKSAREASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ANALYSER_PEAKSAREA_GLOBAL_H
