#ifndef REPORT_PARAMETERIZATION_GLOBAL_H
#define REPORT_PARAMETERIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORT_PARAMETERIZATION_LIBRARY)
#  define REPORT_PARAMETERIZATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPORT_PARAMETERIZATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORT_PARAMETERIZATION_GLOBAL_H
