#ifndef DOCKWIDGETTITLEBAR_GLOBAL_H
#define DOCKWIDGETTITLEBAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DOCKWIDGETTITLEBAR_LIBRARY)
#  define DOCKWIDGETTITLEBARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DOCKWIDGETTITLEBARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DOCKWIDGETTITLEBAR_GLOBAL_H
