#ifndef COPY_BLOCKTESTS_GLOBAL_H
#define COPY_BLOCKTESTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COPY_BLOCKTESTS_LIBRARY)
#  define COPY_BLOCKTESTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COPY_BLOCKTESTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COPY_BLOCKTESTS_GLOBAL_H
