#ifndef REPORT_QUANTITY_GLOBAL_H
#define REPORT_QUANTITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORT_QUANTITY_LIBRARY)
#  define REPORT_QUANTITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPORT_QUANTITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORT_QUANTITY_GLOBAL_H
