#ifndef TECHREPORT_CALIBRATION_GLOBAL_H
#define TECHREPORT_CALIBRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TECHREPORT_CALIBRATION_LIBRARY)
#  define TECHREPORT_CALIBRATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TECHREPORT_CALIBRATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TECHREPORT_CALIBRATION_GLOBAL_H
