#ifndef ABOUTMODULS_GLOBAL_H
#define ABOUTMODULS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABOUTMODULS_LIBRARY)
#  define ABOUTMODULSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ABOUTMODULSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ABOUTMODULS_GLOBAL_H
