#ifndef TEST_EDITOR_GLOBAL_H
#define TEST_EDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEST_EDITOR_LIBRARY)
#  define TEST_EDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEST_EDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEST_EDITOR_GLOBAL_H
