#ifndef TEST_CALIBRATION_GLOBAL_H
#define TEST_CALIBRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEST_CALIBRATION_LIBRARY)
#  define TEST_CALIBRATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEST_CALIBRATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEST_CALIBRATION_GLOBAL_H
