#ifndef REPORT_QUALITY_GLOBAL_H
#define REPORT_QUALITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORT_QUALITY_LIBRARY)
#  define REPORT_QUALITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPORT_QUALITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORT_QUALITY_GLOBAL_H
