<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<scenario>
  <name>Protocol&amp;Device</name>
  <Points>
    <item>
      <name>OpenProtocol</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>FileName</name>
          <value>../scenario/Template_96(5)_Verification.trt</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>OpenDevice</name>
      <receiver>run</receiver>
    </item>
    <item>
      <name>OpenBlock</name>
      <receiver>run</receiver>
    </item>
    <item>
      <name>ScanCoefficients</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>TPeaks,Amplitude</name>
          <value></value>
        </item>
        <item>
          <name>Default_Param</name>
          <value>yes</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>RunProtocol</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>Hold</name>
          <value>stop_after_execution</value>
        </item>
        <item>
          <name>VideoImage</name>
          <value>On</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>AnalysisProtocol</name>
      <receiver>analysis</receiver>
      <Parameters>
        <item>
          <name>FileName</name>
          <value></value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>OpenBlock</name>
      <receiver>run</receiver>
    </item>
    <item>
      <name>ScanCoefficients</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>TPeaks,Amplitude</name>
          <value></value>
        </item>
        <item>
          <name>Default_Param</name>
          <value>yes</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>RunProtocol</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>Hold</name>
          <value>stop_after_execution</value>
        </item>
        <item>
          <name>VideoImage</name>
          <value>On</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>AnalysisProtocol</name>
      <receiver>analysis</receiver>
      <Parameters>
        <item>
          <name>FileName</name>
          <value></value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>OpenBlock</name>
      <receiver>run</receiver>
    </item>
    <item>
      <name>ScanCoefficients</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>TPeaks,Amplitude</name>
          <value></value>
        </item>
        <item>
          <name>Default_Param</name>
          <value>yes</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>RunProtocol</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>Hold</name>
          <value>stop_after_execution</value>
        </item>
        <item>
          <name>VideoImage</name>
          <value>On</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>AnalysisProtocol</name>
      <receiver>analysis</receiver>
      <Parameters>
        <item>
          <name>FileName</name>
          <value></value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>OpenBlock</name>
      <receiver>run</receiver>
    </item>
    <item>
      <name>ScanCoefficients</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>TPeaks,Amplitude</name>
          <value></value>
        </item>
        <item>
          <name>Default_Param</name>
          <value>yes</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>RunProtocol</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>Hold</name>
          <value>stop_after_execution</value>
        </item>
        <item>
          <name>VideoImage</name>
          <value>On</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>AnalysisProtocol</name>
      <receiver>analysis</receiver>
      <Parameters>
        <item>
          <name>FileName</name>
          <value></value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>OpenBlock</name>
      <receiver>run</receiver>
    </item>
    <item>
      <name>ScanCoefficients</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>TPeaks,Amplitude</name>
          <value></value>
        </item>
        <item>
          <name>Default_Param</name>
          <value>yes</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>RunProtocol</name>
      <receiver>run</receiver>
      <Parameters>
        <item>
          <name>Hold</name>
          <value>stop_after_execution</value>
        </item>
        <item>
          <name>VideoImage</name>
          <value>On</value>
        </item>
      </Parameters>
    </item>
    <item>
      <name>AnalysisProtocol</name>
      <receiver>analysis</receiver>
      <Parameters>
        <item>
          <name>FileName</name>
          <value></value>
        </item>
      </Parameters>
    </item>
  </Points>
</scenario>